server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/"

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_get
          # uri: "http://localhost:8001"
          uri: "lb://CLOUD-PAYMENT-SERVICE"
          predicates:
            - Path=/payment/get/**

        - id: payment_lb
          # uri: "http://localhost:8001"
          uri: "lb://CLOUD-PAYMENT-SERVICE"
          predicates:
            - Path=/payment/lb/**
            # - Cookie=username,zzyy
            # - Header=X-Request-Id, \d+
